name: wakeup
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: ^4.6.5
  url_launcher: ^6.1.10
  wakelock: ^0.6.1+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: ClockFont
      fonts:
        - asset: assets/fonts/digital-7 (mono).ttf
          weight: 400
